astree.o: astree.cpp astree.h auxlib.h symtable.h \
stringset.h lyutils.h yyparse.h
auxlib.o: auxlib.cpp auxlib.h
lyutils.o: lyutils.cpp lyutils.h astree.h auxlib.h symtable.h yyparse.h
main.o: main.cpp astree.h auxlib.h symtable.h lyutils.h yyparse.h \
 stringset.h
stringset.o: stringset.cpp stringset.h
symtable.o: symtable.cpp astree.h auxlib.h symtable.h \
lyutils.h yyparse.h
